### ISSUE TITLE
Create an executable file for Windows OS as an installation runtime

### ISSUE THREAD

**Issue by ihhub** [ihhub/fheroes2#942]
We would like to make our game installation even more user-friendly. As we know an user needs to download a demo version of the game as a bare minimum to play it. We have a bat script to do this.

From user's perspective it's good that he could run a simple application (setup) which would extract our archive with the game and run demo downloading script. We could explore 7z SFX Builder solution to do so. Please note that there are users who already have a licensed full version of the game so for them we need to give an option to just extract our game without downloading the demo version.

**Comment by qarkai** [comment]
Do you consider third-party installers like Inno Setup?

**Comment by ihhub** [comment]
Hi @qarkai , anything which is doable by automation of our CI\CD pipeline could be used for this purpose.

**Comment by ihhub** [comment]
I've checked this tool. We might need to use an older version in order to create an executable file which could be run by old Windows versions.

**Comment by qarkai** [comment]
I prepared Inno Setup script which produces installer `fheroes2-<version>-<x86|x64>-<SDL1|SDL2>.exe`. It could be used in appveyor.yml as
```yml
after_build:
  - cmd: cd C:\projects\fheroes2
  - cmd: iscc fheroes2.iss "/DBuildDir=C:\projects\fheroes2\build\%platform%\%configuration%" /DPlatform=%platform% /DDeployConfName=%deploy_conf_name%
```
But I don't know how to install iscc (Inno Setup command-line compiler) inside CI/CD image.
I can open PR which simply adds fheroes2.iss script.
